server:
  port: 12231

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: test
      url: jdbc:mysql://127.0.0.1:3306/mybatis_demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useSSL=false&serverTimezone=Hongkong
      username: root
      password: 123456
      initial-size: 10
      max-wait: 10000
      maximum-pool-size: 100
      max-active: 100
      max-idle: 10
      minIdle: 2

spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.springbootmybatis.model  # 注意：对应实体类的路径
